Traceback (most recent call last):
  File "/Users/tianqingzhou/Library/Caches/pypoetry/virtualenvs/cipher-tz2372-dVemWyYh-py3.8/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/tianqingzhou/Library/Caches/pypoetry/virtualenvs/cipher-tz2372-dVemWyYh-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/tianqingzhou/Library/Caches/pypoetry/virtualenvs/cipher-tz2372-dVemWyYh-py3.8/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/tianqingzhou/Library/Caches/pypoetry/virtualenvs/cipher-tz2372-dVemWyYh-py3.8/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/tianqingzhou/Library/Caches/pypoetry/virtualenvs/cipher-tz2372-dVemWyYh-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Users/tianqingzhou/Library/Caches/pypoetry/virtualenvs/cipher-tz2372-dVemWyYh-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/tianqingzhou/Library/Caches/pypoetry/virtualenvs/cipher-tz2372-dVemWyYh-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import cipher_tz2372

print(cipher_tz2372.__version__)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-6ef3d83dc4c6>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mimport[0m [0mcipher_tz2372[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0mprint[0m[0;34m([0m[0mcipher_tz2372[0m[0;34m.[0m[0m__version__[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'cipher_tz2372'
ModuleNotFoundError: No module named 'cipher_tz2372'

